### ISSUE TITLE
Error using Popen in debug mode but no error executing normally

### ISSUE THREAD

**Issue by tryjude** [rammie/pdfjinja#1]
I'm using this library successfully to fill in PDF form values when I execute my program normally (not in debug mode). However, if I execute my application in _debug_ mode inside of my IDE (PyCharm), I get the following stack trace:

`File "/Users/me/work/server/venv/lib/python2.7/site-packages/pdfjinja.py", line 220, in __call__
  filled = PdfFileReader(self.exec_pdftk(self.rendered))
File "/Users/me/work/server/venv/lib/python2.7/site-packages/pdfjinja.py", line 194, in exec_pdftk
  p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
  errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
  raise child_exception
OSError: [Errno 2] No such file or directory`

It appears as though the snippet of code in question is inside `pdfjinja.py` at line 194: 

``` python
        p = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
        stdout, stderr = p.communicate(fdf)
```

I've done some googling that points to PIPE being a potential problem with Popen. Here is the blog article:

http://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/

Would it be possible to update the exec_pdftk function so that it addresses this? 

Again, this only seems to be a problem when running my code inside my IDE in debug mode. Normal execution works just fine. Therefore, this might not be a high priority issue but I thought I'd report it anyway.

Thanks for providing this tool!

**Comment by rammie** [comment]
Thanks for the bug report. The error message:

```
... OSError: [Errno 2] No such file or directory
```

refers to the pdftk program. it sounds like the IDE is changing your environment variables such that the pdftk executable cannot be found. You can fix this by configuring the PATH environment variable in your IDE settings. Set its value to the folder that contains the pdftk.exe file. See: http://stackoverflow.com/a/22899916 

I'm closing this issue for now since it is related to IDE configuration and not the package itself., but feel free to respond to this if you're still having problems.

**Comment by tryjude** [comment]
THANK YOU!

Really appreciate the quick reply. You also were bang on with your
suggestion. I added the PATH to my debug configuration and now it works!

The strange thing is that I can run it in normal mode inside PyCharm without
configuring PATH. Weird...

Anyway, I just wanted to say thanks again. Appreciate it.

Have a great day!

-- J

On Wed, Nov 18, 2015 at 9:49 AM, Ram notifications@github.com wrote:

> Thanks for the bug report. The error message:
> 
> ... OSError: [Errno 2] No such file or directory
> 
> refers to the pdftk program. it sounds like the IDE is changing your
> environment variables such that the pdftk executable cannot be found. You
> can fix this by configuring the PATH environment variable in your IDE
> settings. Set its value to the folder that contains the pdftk.exe file.
> See: http://stackoverflow.com/a/22899916
> 
> I'm closing this issue for now since it is related to IDE configuration
> and not the package itself., but feel free to respond to this if you're
> still having problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rammie/pdfjinja/issues/1#issuecomment-157737356.

## 

_Judem: +1 519 200 8205e: tryjude@gmail.com tryjude@gmail.com_

**Comment by flooie** [comment]
@tryjude having the exact same issue with pycharm

**Comment by rammie** [comment]
This is an issue with you enviroment. Please ensure that pdftk is on the PATH in PyCharm.

**Comment by pmourelle** [comment]
I came to a similar issue, without environment issue, just from terminal on OSX 10.13.3.
Issue was a bad-built pdftk, now working fine -> https://stackoverflow.com/questions/39750883/pdftk-hanging-on-macos-sierra
