### ISSUE TITLE
xrange NameError

### ISSUE THREAD

**Issue by tyleralev** [rammie/pdfjinja#18]
I have been getting this issue with the example code and know it is in issue dealing with the conversion from python 2 to python 3. With xrange being defined as range in python 3. Having trouble figuring out this problem and have run the all python scripts for python 3 support in the main GitHub file. I am also using an anaconda environment in jupyter notebooks which may be causing some issues as well. Any advice would be greatly appreciated.

![image](https://user-images.githubusercontent.com/41857868/50026435-f1c2b400-ffb6-11e8-8b65-456a5286e6c6.png)

**Comment by moccand** [comment]
Did you get a workaround ?

**Comment by TileThePlane** [comment]
I have a workaround here -> https://github.com/TileThePlane/pdfjinja

 In your requirements.txt include the following:
-e git+http://github/TileThePlane/pdfjinja#egg=pdfjinja==1.0.0
