### ISSUE TITLE
Unchecked checkboxes not exported in output

### ISSUE THREAD

**Issue by moccand** [rammie/pdfjinja#8]
Hi,
Is there a way to keep checkboxes in output event if they are not checked ?

with thefollowing code my 2 checkboxes are shown and checked : 
```
rendered_pdf = template_pdf({
    'ck1': 'Yes',
    'ck2': 'Yes'})
```
but using 

```
rendered_pdf = template_pdf({
    'ck2': 'Yes'})
```

i thought the first checkbox would stay unchecked in te result, but it is not shown at all.

Thanks

**Comment by rammie** [comment]
The checkbox in the example is now working as expected.
